var property = {
	// common
	saveSuccessfully:"保存成功！",
	saveFailed:"保存失败！",
	deleteSuccessfully:"删除成功！",
	deleteFailed:"删除失败！",
	serviceUnknown:"未知服务异常",
	notRepeatSubmit:"请不要重复提交!",
	BadRequest:"服务器响应异常!",
	// navigation
	giveUpOrder:"您确定现在要放弃本次订餐?或点击“取消”继续点餐",
	giveUpOrdering:"您确定终止订餐流程返回首页？",
	giveUpLogin:"您确定现在要放弃本次登录?",
	notInOper:"肯德基宅急送服务时间为每天10:00至22:00。目前不是服务时间，敬请谅解！",
	exitOrderToIndex:"请确认是否要退出订餐，回到首页？",
	loginAgain:"您确定要重新登录吗？",
	favoriteBtn:"请使用浏览器的添加收藏夹功能收藏本网站!",
	// 登录
	EorPNotcorrect:"请填写正确格式的手机或电子邮箱！",
	EorPNotNull:"请填写正确格式的手机或电子邮箱！",
	emailNotcorrect:"请填写正确的邮箱地址！",
	emailNotNull:"请填写正确的邮箱地址！",
	mobNotcorrect:"请填写正确的手机号！",
	mobiNotNull:"请填写正确的手机号！",
	pwdNotNull:"请输入密码！",
	//mobiMailPwd:"请输入正确的手机号、邮件地址和密码!",
	passNotCorrect:"密码不正确，请重新输入！",
	// 用户
	pleaseInputEmail:"请输入邮箱地址",
	customerNameTip:"请输入姓名",
	customerNameNotNull:"姓名不能为空",
	customerNameNotRight:"用户姓名只能输入汉字、英文、数字、_、-、.",
	genderNotChoose:"请选择性别",
	pleaseChoosePhone:"请选择联系电话！",
	pleaseChooseAddress:"请选择送餐地址！",
	inputPassword:"请输入密码",
	inputPasswordAgain:"请再次输入密码",
    twoPasswordsDoNotMatch : "两次填写的密码不一致，请重新输入。",
    EorPasswordFormat : "输入密码为6~16个数字或字母",
    invaildStringError : "请勿输入非法字符！",
	inputCode:"请输入验证码",
    EorInputCode : "验证码不正确",
	emailExist:"您的邮箱已经存在，是否进行登录?",
	emailExist2:"该电子邮箱已存在， 并已设置密码保护，是否确定以该邮箱登录？",
	emailSendFail:"邮件发送失败,请稍后再试！",
	setPasswordSuccessfully:"密码设置成功！",
	unlockPasswordSuccessfully:"密码解除成功！",
	notSavePassword:"密码未保存，请点击确认按钮保存密码。",
	notLonger:'姓名请勿超过12个字',
	deliveryTime:"送餐时间：",
	afterSubmit:"成功提交订单后，预计",
	timeArrive:"分钟左右送达。",
    currentLater:"预约当日稍晚时间送餐。",
    noMatch:"查无结果",
    addressFalse:"请填写如楼号/门牌号/室号等数字开头的详细地址！",
    addressBlank:"请填写正确的详细地址",
    validateCode:"验证码",
    codeNotNull:"验证码不能为空",
    msgSending:"正在发送手机验证码",
    sendFailed:"短信验证码发送失败，请稍后再试！",
    addressDel:"删除地址的验证邮件已经发送至[{0}],请注意查收",
    cancelLift:"取消解除",
    plsRefresh:"看不清？点击刷新",
    resetMail:"设置/重置密码邮件已发送至[{0}],请注意查收。",
    noCodeWarn:"您选择了不设置密码！您的送餐地址下次将显示为：",
    hour:"时",
    min:"分送到",
	// 电话
    mobile:"手机",
    fixedPhone:"座机",
	mobileTip:"请填写手机号码",
	areaCodeTip:"请输入送餐城市拼音首字母",
	telephoneTip:"请填写座机号码",
	mobiTelephone:"请填写联系电话！",
	areaCodeNotNull:"区号不正确",
	teleNotNull:"请填写座机号码！",
	areaCodeNotCorrent:"请填写正确的城市区号！",
	teleNotCorrent:"请填写正确的座机号！",
	extensionNumNotCorrent:"请填写正确的分机号！",
	mobileExitCantAdd:"该电话已存在，无需重复添加！",
//	telephoneExitCantAdd:"该座机已存在，无需重复添加!",
	phoneCantDelete:"该手机不能删除！",
	deletePhoneWarn:"您确定要删除该电话号吗？",
	phoneNotSelected:"请选择本次联系电话。",
	overTenPhone:"对不起！你已经有10个联系电话！如有需要请修改其他联系电话！",
	// 地址
	cityTip:"请输入城市名",
	mainAddressTip:"请输入地址关键字",
	suppleMentalAddressTip:"例如：10弄1号。如此处与路名/小区名填写内容有矛盾，视为无效订单。",
	addressRepeat:"输入的地址重复！",
	cityNotNull:"请填写送餐城市！",
	pleaseChooseCityFirst:"请先填写送餐城市！",
	pleaseChooseMainAddress:"请填写送餐地址中的路名/小区名。",
	communityNotNull:"请先填写路名/小区名！",
	communityDescNotNull:"请先填写路名/小区名！",
	suppleMentalAddressStart:"请填写详细地址，如：10弄1号101室",
	suppleMentalAddressTooLong:"详细送餐地址不能超出最大长度，请重新输入！",
	cityNotLegal:"送餐城市输入不合法，请重新输入！",
	mainAddressNotLegal:"路名/小区名输入不合法，请重新输入！",
	inputCityName:"请填写城市名称",
	inputMainAddress:"请填写路名/小区名",
	inputSuppleMentalAddress:"请填写补全地址",
	deleteAddressWarn:"您确定要删除该地址吗？",
	addressNotInDelivery:"输入的地址不在外送范围之内！",
	addressNotInDeliveryHelp:"很抱歉，可能由于送餐范围调整，该地址目前不在我们的送餐范围内。请致电4008823823寻求帮助。",
	storeClosed:"很抱歉，由于送餐范围调整，该地址目前不在我们的送餐范围内，请重新选择送餐地址。",
	storeStop:"很抱歉，可能由于送餐范围调整，该地址目前不在我们的送餐范围内，敬请谅解",
	serviceInDeliveryTime:"很抱歉，该地址我们仅在10:00-22:00 提供送餐服务。",
    addressNotSelect:"请选择您的送餐地址。",
    addressExitCantAdd:"该地址已存在，无需重复添加！",
    overTenAddress:"对不起！你已经有10个送餐地址！如有需要请修改其他送餐地址！",
    notFindAddress:"地址不在外送范围之内！",
  
	// 餐厅
	pleaseChooseStore:"请选择餐厅！",
	storeNotOpen:"该餐厅未开业，不能订餐!",
	storeClose:"该餐厅已关店，不能订餐！",
	storeTempClose:"该餐厅已临时关店，不能订餐！",
	storeOtherReason:"该餐厅因未知状况，不能订餐！",
	
	notExsitRecord:"很抱歉，您输入的电子邮箱或手机不存在相关记录。",
	setPasswordValidate:"设置/重置密码链接已过期，请重新设置",
	
	errorOrderItemsNum:"请选择正确的数量（份数区间1-{0}份）！",
	errorCartNum:"同一餐点您订购的份数不能大于{0}份！",
    infoMinOrderItemNum: "您订购的份数至少需要1份。",
    infoMaxOrderItemNum: "商品数量最多为1！",
    orderItmesIsNull: "你提交的订单内容不能为空，请选择点餐。",
    promItemNumIsNull: "您还没输入的优惠商品数量！",
    errorPromItmesNum: "您点击的优惠商品数量已经超过活动数量！",
	delOrderItem:"您确定要删除该餐点？",
    delAllOrderItem: "您确定要删除所有餐点？",
    checkOrderTip:"请输入您订餐时曾使用的电子邮箱或手机号码。",
    delAddrReturn:"删除成功，请返回发送邮件前页面并刷新！",
    
    netError:"服务未响应，请稍后重试！",
	payError:"支付未成功，请重新选择支付方式",
	payProcessed:"支付出现问题，订单已提交4008823823电话服务台，稍后我们的工作人员会与您联系！",
	paySuccess:"支付成功",
	notOnlinePay:"您本次订餐所选择的地址不支持网上支付，该地址只支持货到现金付款。",
	infoChooseBank: "请选择您要支付的网上银行",
	payMoneyError:"网上支付的金额与订单金额不符合，请拨打4008823823寻求客服帮助，由此造成的不便，敬请谅解！",
	timeOntOnlinePay:"您本次订餐所在时间段不支持网上支付",

    promotionCodeText: "输入优惠代码",
	promotionCodeNotFound:"您输入的优惠代码不正确，请重新填写。",
	promotionCodeNotNull:"优惠代码不能为空，请填写。",
	orderNotFound:"订单不存在",
	orderCandcelled:"订单已取消，不能查看订单明细！",
	orderModified:"订单已修改，不能查看订单明细！",
	userNotFound:"用户失效请重新登录。",
	orderEscalation:"订单下单出现问题，请拨打4008823823寻求客服帮助，由此造成的不便，敬请谅解！",
	ErrorCode_306:"优惠暂时不能使用，请稍后再试！",
	donate:"请您输入捐款金额",
	donateVaild:"捐款金额请输入1-499元之间的整数",
	WarningCode_2:"优惠条件不满足，订单中优惠产品被清除！",
		
	/** 转网用户话术*/
	validateSuccess:"恭喜您已验证成功，本次网上订餐，您可以享受优惠“产品金额满29元免外送费”，结算时自动执行，点击确认开始订餐。",
	validateError:"验证码有误，请重新输入",
	getCodeOverNum:"很抱歉，您今日获取验证码的次数已超过限定，请明日再来尝试。",
	getCodeFaild:"验证码发送失败，请稍后再试。",
	getCodeSuccess:"验证码发送成功。",
	timeOutRange:"每日10:00~22:00登录并验证订餐，才可享受“产品满29元免外送费”优惠哦。<br><br>知道了，我不参与优惠活动。&nbsp; 我要继续订餐。",

	/** 订单确认话术*/
	orderIsBlank:"您提交的订单内容不能为空，请先选择餐点。",
	chosePromotion:"您有已选择的优惠品项未加入订单。是否继续下一步？",
	/**home.js*/
    couponTitle:"产品已加入购物车。购买此产品还可享受",
    promotionNotice:"注：您可享受“网订产品满29元免外送费”优惠，结算时自动执行",
    moreDetail:'查看详情»',	
    noWarn:'我知道，不要再提醒了哦！',
    avaliableTime:'供应时间：',
    avaliableDate:'供应日期：',
    avaliableZone:'供应地区：',
    /**index.js*/
    noMatchInfo:"未找到匹配的送餐信息,是否以新用户身份继续下一步?",
    /**PageEffect.js*/	
    breakfast:"早餐",
    meal:"正餐",
    snack:"夜宵",
    outOfservice:"您所选择的送餐区域目前不提供{0}的网上订餐服务,敬请谅解.",
    contactInfo:"联系电话",
    ThroughoutTheYear:"全年"
};

var pageMessage ={
		colon :'：',
		period:'。',
		or:'或',
		yun:"元",
		fen:"份",
		subtotal:"小计",
		deliverFee:"外送费",
		total:"合计",
		/**customer.js*/
		customer_remind:"友情提示",
		customer_setCode:"设置密码",
		customer_continueOrder:"继续点餐",
		/**common*/
		common_yuan:"元",
		common_invoiceTitle:"发票抬头",
		common_Mr:" 先生",
		common_Ms:" 女士",
		common_nothing:"无",
		/**check.js*/
	    check_customerInformation:"个人信息",
		check_name:"顾客姓名：",
		check_telephone:"联系电话：",
		check_address:"送餐地址：",
		check_orderItems:"订单详情",
		check_no:"序号",
		check_productName:"品名",
		check_unitPrice:"单价",
		check_quantity:"数量",
		check_promotionPrice:"优惠价",
		check_subtotal:"小计",
		check_remark:"优惠备注",
		check_subtotal2:"小&emsp;计：",
		check_deliveryFeeDeliveryFee:"外送费",
		check_total:"总金额：",
		check_donate:"另有爱心捐款：",
		check_payment:"支付方式：",
		check_cashOnDelivery:"货到现金付款",
		check_OnlinePayment:"网上支付",
		check_DoyourNeedInvoice:"是否需要发票：",
		check_anyOtherRequirement:"其它送餐要求：",
		check_backUpTelephone:"其他联系人及电话：",
		check_close:"关闭详情 ",
		check_backUpTelephone2:"备用联系手机：",
		check_cnsumbit:"提交",
		check_ensumbit:"",
		check_deliveryTo:"送到",
		check_estimated:"预计",
		/**cart.js*/
		cart_expand:"[展开]",
		cart_retract:"[收起]",
		
		/**pay.js*/
		pay_15Characters:"限15个字以内",
		pay_DonationCash:"爱心捐款只能以“货到现金付款”方式支付给外送骑手。</br>您仍可使用“网上支付”方式支付您的订单。(除爱心捐款部分)",
		pay_499Integer :"1-499元之间的整数",
		pay_chooseBank:"请选择网上支付的银行！",
		pay_InvoiceTitle:"请输入发票抬头！",
		pay_CorrectInvoiceTitle:"请输入正确的发票抬头！",
		pay_40Characters:"发票抬头不能超过40个字符（20个汉字）！",
		pay_drinkToIce:"比如饮料去冰，限20字以内",
		pay_correctRequirements:"请输入正确的其他送餐要求！",
		pay_enterThePhone:"只输入手机号码",
		pay_correctMobile:"请输入正确格式的手机号码！",
		pay_correctDonation:"请输入正确格式的爱心捐款！",
		pay_chosenPayment:"您还没选择支付方式",
		pay_paymentFailed:"支付失败，请重新支付！",
		pay_correctBackUp:"请输入正确的备用联系电话",
		/**base.js*/
		base_title:"肯德基宅急送",
		base_confirm:"确定",
		base_cancle:"取消",
        base_quitDonate:"放弃捐款",
        base_nextStep:"下一步",
        base_backCunrrent:"返回当前页面",
        base_addOrder:"加入订单",
        base_noNeed:"不需要",
        base_continueOrder:"继续订餐",
        base_loginLater:"稍后登录",
        /**home.js*/
        home_Per:'/份',
        Yuan_Per:'元/份'
};
//用于后台服务code对应的Message
var codeMessage ={
		error2:"未知服务异常",
		//前台服务
		error001:"餐厅仅在({0}-{1})提供订餐服务！",
		//客户服务
		error100:"被禁止客户",
		error101:"客户不存在",
		error102:"客户为密码用户，需提供密码进行登录",
		error103:"客户输入错误的密码",
		error104:"客户使用手机号码登录，发现对应多个email",
		error106:"客户使用手机号码登录，但仍然需要输入email以唯一确定一个账户",
		error107:"客户使用的Email已经被使用",
		error108:"地址未找到",
		error109:"地址与客户信息不匹配",
		error110:"电话未找到",
		error111:"电话与客户信息不匹配",
		error112:"用户同步密码异常",
		error113:"客户使用的电话已存在",
		error114:"用户同步密码异常",
		error115:"Email格式不正确",
		error116:"用户为OS2IOS转网用户",
		error117:"OS2IOS转网用户验证码错误",
		//菜单服务
		error201:"餐厅菜单未找到",
		error202:"分类中菜单未找到",
		error203:"套餐子产品未找到",
		error204:"菜单分类ID不能为空",
		error205:"菜单ID不能为空",
		error206:"菜单类型不能为空",
		error207:"该餐厅不存在",
		error208:"该套餐不可售",
		error209:"首页广告无大图片",
		error210:"首页广告无小图片",
		error212:"首页无文字链接",
		error250:"日期格式错误",
		error251:"菜单与分类关系未找到",
		//地址服务
		error20:"门店未找到",
		error21:"城市未找到",
		error22:"区域未找到",
		error24:"街道、路未找到",
		error25:"地址未找到",
		error26:"分商圈停单 不在送餐范围内",
		error27:"餐厅停单",
		error28:"市场未找到",
		error29:"大区未找到",
		//订单服务
		error400:"订单不存在",
		error401:"订单格式不正确",
		error402:"产品不存在",
		error403:"产品格式不正确",
		error404:"用户不存在",
		error405:"填写的送餐时间必须晚于最快送餐时间",
		error406:"不在订餐时间内",
		error407:"不在餐厅订餐时间内",
		//error408:"无法送餐",
		error408:"很抱歉，无法送餐，请致电4008823823寻求帮助。",
		error409:"产品数量不正确",
		error410:"产品初始化失败",
		error411:"POS机连接不上",
		error412:"外拨连接不上",
		error413:"外拨数据连接错误",
		error414:"外拨参数错误",
		error415:"外拨数据插入错误",
		error416:"外拨其他错误",
		error417:"SON数据格式错误",
		error418:"邮件参数错误",
		error419:"邮件JSON数据错误",
		error420:"邮件发送错误",
		error421:"pos服务连接失败",
		error422:"订单未支付",
		error430:"订单金额错误",
		error431:"订单项为空",
		error432:"预约时间有误",
		error433:"时间格式错误",
		error434:"产品价格错误",
		error435:"订单支付金额不一致",
		error437:"订单产品已过时效期",
		//优惠服务
		error301:"产品数量超过最大值",
		error302:"产品不存在",
		error303:"订购产品不合法",
		error304:"产品售完",
		error305:"优惠未找到",
		error306:"使用优惠时给定非法优惠",
		error307:"订单内存在不合法优惠",
		error308:"必须给定B产品与数量",
		error309:"优惠代码未找到",
		error311:"数据验证错误",
		error312:"优惠代码更新失败",
		error313:"餐厅不存在",
		error314:"优惠不合法",
		error315:"订单不合法",
		error316:"优惠代码不在使用期限内",
		error317:"已使用优惠代码，不能重复使用",
		error318:"不满足该优惠代码对应的优惠"
};